### ISSUE TITLE
pip requirements file outdated?

### ISSUE THREAD

**Issue by groovecoder** [oyiptong/splice#182]
I ran the steps listed in README to get my virtual environment set up. Then I tried to run `manage.py db init`

```
ImportError: No module named alembic
...
ImportError: No module named mock
```
I tried installing some, but I ran into this:
```
(splice-env)lcrouch-14912:splice lcrouch$ pip install mock
Downloading/unpacking mock
  Downloading mock-1.3.0.tar.gz (70kB): 70kB downloaded
  Running setup.py egg_info for package mock
    mock requires setuptools>=17.1. Aborting installation
    Complete output from command python setup.py egg_info:
    mock requires setuptools>=17.1. Aborting installation
```

**Comment by oyiptong** [comment]
Hey @groovecoder. I'm guilty of not having kept this documentation up-to-date.
That needs to be fixed, e.g. `db init` isn't a required step anymore I think.

However, the pip install failing is not a good thing. It is possibly related to the version of XCode/clang you are running.

```
$ clang --version
Apple LLVM version 7.0.0 (clang-700.1.76)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
```
I have this version of clang installed and it requires a certain compiler flag to be set before pip install.

pip will happily not report an error on compiling gevent unfortunately. I just reported this in #171

**Comment by oyiptong** [comment]
Can you please try to setup the project as follows?

```
$ CFLAGS='-std=c99' ./setup-project.sh
```

**Comment by ncloudioj** [comment]
This has been fixed in b3f88d6

**Comment by groovecoder** [comment]
I reported the issue in a confusing way, but this is certainly not fixed. The `README.md` needs updating.

I have the same `clang --version`. So, I tried starting over. I skipped `manage.py db init` and I got:
```
(splice-env)lcrouch-14912:splice lcrouch$ manage.py db migrate
...
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  database "mozsplice_campaigns" does not exist
```
So, I created both of the databases:
```
postgres=# create database mozsplice_campaigns;
CREATE DATABASE
postgres=# create database mozsplice;
CREATE DATABASE
```
Now I get a different error:
```
(splice-env)lcrouch-14912:splice lcrouch$ manage.py db migrate
...
alembic.util.CommandError: Target database is not up to date.
```
I sent https://github.com/oyiptong/splice/pull/187 with the things I had to do differently to get thru the README.
